/**
 * `node-doctor ci install` — scaffold a GitHub Actions workflow that runs the
 * baseline-delta (report only what a PR introduced), posts a PR summary, and
 * publishes a commit status. A scaffolder, not a gate: non-destructive if the
 * workflow already exists.
 */

import { writeFile, mkdir, stat } from "node:fs/promises";
import { join, resolve } from "node:path";

const WORKFLOW_PATH = ".github/workflows/node-doctor.yml";

const WORKFLOW_TEMPLATE = `# Generated by \`node-doctor ci install\`. Reports only findings a PR introduces.
name: node.doctor

on:
  pull_request:
  push:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write   # PR summary comment + inline review
  statuses: write        # commit status with the health score
  security-events: write # optional SARIF upload

jobs:
  node-doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # baseline delta needs history

      - name: node.doctor
        uses: DhiravPatel/node_doctor@v0
        with:
          directory: .
          blocking: error         # fail the check only on findings the PR introduced
          sarif-out: node-doctor.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: node-doctor.sarif
        continue-on-error: true
`;

const exists = async (p: string): Promise<boolean> => {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
};

export interface CiInstallResult {
  path: string;
  action: "created" | "skipped";
}

export const installCiWorkflow = async (cwd: string): Promise<CiInstallResult> => {
  const target = resolve(cwd, WORKFLOW_PATH);
  if (await exists(target)) {
    return { path: target, action: "skipped" };
  }
  await mkdir(join(resolve(cwd), ".github", "workflows"), { recursive: true });
  await writeFile(target, WORKFLOW_TEMPLATE);
  return { path: target, action: "created" };
};
