import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runTextScan, type TextDiagnostic } from "../../src/core/text-scan.ts";
import type { NodeDoctorConfig } from "../../src/core/config.ts";
import { k8sPrivilegedContainer } from "../../src/diagnostics/k8s/k8s-privileged-container.ts";
import { k8sHostNamespace } from "../../src/diagnostics/k8s/k8s-host-namespace.ts";
import { k8sMissingResourceLimits } from "../../src/diagnostics/k8s/k8s-missing-resource-limits.ts";

// The bucket's index.ts is generated by the orchestrator, so the list is built
// here from the diagnostic modules directly.
const K8S_DIAGNOSTICS: TextDiagnostic[] = [k8sHostNamespace, k8sMissingResourceLimits, k8sPrivilegedContainer];

/** Opt-in rules are off unless the config asks for them. */
const LIMITS_ON: NodeDoctorConfig = { diagnostics: { "k8s-missing-resource-limits": "warn" } };

/** Run the K8s diagnostics over a single fabricated file. */
const scan = async (name: string, content: string, config?: NodeDoctorConfig): Promise<string[]> => {
  const dir = await mkdtemp(join(tmpdir(), "nd-k8s-"));
  try {
    const full = join(dir, name);
    await mkdir(join(full, ".."), { recursive: true });
    await writeFile(full, content);
    const findings = await runTextScan(dir, { textDiagnostics: K8S_DIAGNOSTICS, config });
    return findings.map((f) => f.diagnostic).sort();
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
};

const DEPLOYMENT_HEAD = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  template:
    spec:
`;

/** A Deployment whose single container carries `containerBody` (8-space indented). */
const deployment = (containerBody: string): string =>
  `${DEPLOYMENT_HEAD}      containers:
        - name: api
          image: ghcr.io/acme/api:1.4.0
${containerBody}`;

describe("k8s-privileged-container", () => {
  test("fires on securityContext.privileged: true in a Deployment", async () => {
    const yaml = deployment(`          securityContext:\n            privileged: true\n`);
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml), ["k8s-privileged-container"]);
  });

  test("fires on allowPrivilegeEscalation: true", async () => {
    const yaml = deployment(`          securityContext:\n            allowPrivilegeEscalation: true\n`);
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml), ["k8s-privileged-container"]);
  });

  test("fires on a block-sequence capabilities.add of SYS_ADMIN", async () => {
    const yaml = deployment(
      `          securityContext:\n            capabilities:\n              drop:\n                - ALL\n              add:\n                - SYS_ADMIN\n`,
    );
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml), ["k8s-privileged-container"]);
  });

  test("fires on a flow-sequence capabilities.add of ALL", async () => {
    const yaml = deployment(`          securityContext:\n            capabilities:\n              add: ["ALL"]\n`);
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml), ["k8s-privileged-container"]);
  });

  test("SILENT on a hardened securityContext", async () => {
    const yaml = deployment(
      `          securityContext:\n            privileged: false\n            allowPrivilegeEscalation: false\n            runAsNonRoot: true\n            capabilities:\n              drop:\n                - ALL\n              add:\n                - NET_BIND_SERVICE\n`,
    );
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml), []);
  });

  test("SILENT on docker-compose with privileged: true", async () => {
    const compose = `version: "3.9"
services:
  db:
    image: postgres:16
    privileged: true
    security_opt:
      - seccomp:unconfined
  web:
    image: nginx
    network_mode: host
`;
    assert.deepEqual(await scan("docker-compose.yml", compose), []);
  });

  test("SILENT on a GitHub Actions workflow", async () => {
    const workflow = `name: ci
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - run: npm test
`;
    assert.deepEqual(await scan(".github/workflows/ci.yml", workflow), []);
  });

  test("SILENT on a Helm template — Go templating is not YAML", async () => {
    const chart = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  template:
    spec:
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            privileged: true
`;
    assert.deepEqual(await scan("charts/api/templates/deployment.yaml", chart), []);
  });

  test("SILENT on a ConfigMap carrying a compose file in a block scalar", async () => {
    const configMap = `apiVersion: v1
kind: ConfigMap
metadata:
  name: compose
data:
  docker-compose.yml: |
    services:
      db:
        privileged: true
        image: postgres:16
`;
    assert.deepEqual(await scan("k8s/configmap.yaml", configMap), []);
  });

  test("SILENT when the privileged block is a commented-out example", async () => {
    const yaml = deployment(`          securityContext:\n            # privileged: true\n            runAsNonRoot: true\n`);
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml), []);
  });
});

describe("k8s-host-namespace", () => {
  test("fires on hostNetwork: true in a Deployment pod spec", async () => {
    const yaml = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      hostNetwork: true
      containers:
        - name: api
          image: api:1
          resources:
            limits:
              memory: 256Mi
`;
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml, LIMITS_ON), ["k8s-host-namespace"]);
  });

  test("fires once per host namespace on a bare Pod", async () => {
    const yaml = `apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  hostPID: true
  hostIPC: true
  containers:
    - name: shell
      image: busybox
      resources:
        limits:
          memory: 64Mi
`;
    assert.deepEqual(await scan("k8s/pod.yaml", yaml, LIMITS_ON), ["k8s-host-namespace", "k8s-host-namespace"]);
  });

  test("SILENT when the host namespaces are false", async () => {
    const yaml = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      hostNetwork: false
      hostPID: false
      containers:
        - name: api
          image: api:1
`;
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml), []);
  });

  test("SILENT on docker-compose network_mode: host", async () => {
    const compose = `services:
  web:
    image: nginx
    network_mode: host
    pid: host
`;
    assert.deepEqual(await scan("compose.yaml", compose), []);
  });
});

describe("k8s-missing-resource-limits", () => {
  test("is opt-in: SILENT by default even with no limits anywhere", async () => {
    const yaml = deployment(`          ports:\n            - containerPort: 8080\n`);
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml), []);
  });

  test("fires when enabled and the container has no resources block", async () => {
    const yaml = deployment(`          ports:\n            - containerPort: 8080\n`);
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml, LIMITS_ON), ["k8s-missing-resource-limits"]);
  });

  test("fires when resources has requests but no limits", async () => {
    const yaml = deployment(
      `          resources:\n            requests:\n              cpu: 100m\n              memory: 128Mi\n`,
    );
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml, LIMITS_ON), ["k8s-missing-resource-limits"]);
  });

  test("SILENT for a container that HAS limits", async () => {
    const yaml = deployment(
      `          resources:\n            requests:\n              cpu: 100m\n            limits:\n              cpu: "1"\n              memory: 512Mi\n`,
    );
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml, LIMITS_ON), []);
  });

  test("distinguishes two containers in one pod by indentation", async () => {
    const yaml = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          image: api:1
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
      containers:
        - name: api
          image: api:1
          resources:
            limits:
              memory: 512Mi
        - name: sidecar
          image: envoy:1.30
          ports:
            - containerPort: 15000
`;
    const findings = await scan("k8s/deployment.yaml", yaml, LIMITS_ON);
    assert.deepEqual(findings, ["k8s-missing-resource-limits"]);
  });

  test("SILENT on a patch fragment that names a container without an image", async () => {
    const patch = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: LOG_LEVEL
              value: debug
`;
    assert.deepEqual(await scan("k8s/overlays/prod/patch.yaml", patch, LIMITS_ON), []);
  });

  test("SILENT when resources is an unresolvable alias", async () => {
    const yaml = deployment(`          resources: *standardResources\n`);
    assert.deepEqual(await scan("k8s/deployment.yaml", yaml, LIMITS_ON), []);
  });

  test("SILENT on a docker-compose service without limits", async () => {
    const compose = `services:
  api:
    image: api:1
    ports:
      - "8080:8080"
`;
    assert.deepEqual(await scan("docker-compose.yaml", compose, LIMITS_ON), []);
  });
});

describe("multi-document YAML", () => {
  test("evaluates each document independently — only the Deployment fires", async () => {
    const yaml = `apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  hostNetwork: true
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      hostNetwork: true
      containers:
        - name: api
          image: api:1
          securityContext:
            privileged: true
          resources:
            limits:
              memory: 256Mi
`;
    assert.deepEqual(await scan("k8s/all.yaml", yaml, LIMITS_ON), [
      "k8s-host-namespace",
      "k8s-privileged-container",
    ]);
  });

  test("a leading --- separator does not hide the first document", async () => {
    const yaml = `---
apiVersion: v1
kind: Pod
metadata:
  name: p
spec:
  hostIPC: true
  containers:
    - name: c
      image: busybox
`;
    assert.deepEqual(await scan("k8s/pod.yaml", yaml), ["k8s-host-namespace"]);
  });
});

describe("non-Kubernetes YAML corpus stays silent", () => {
  const corpus: Array<[string, string]> = [
    [
      "openapi.yaml",
      `openapi: 3.0.3\ninfo:\n  title: API\n  version: "1"\npaths:\n  /health:\n    get:\n      responses:\n        "200":\n          description: ok\n`,
    ],
    [
      ".gitlab-ci.yml",
      `image: node:22\nstages:\n  - test\ntest:\n  stage: test\n  services:\n    - docker:dind\n  variables:\n    DOCKER_TLS_CERTDIR: ""\n  script:\n    - npm test\n`,
    ],
    [
      "charts/api/values.yaml",
      `image:\n  repository: ghcr.io/acme/api\n  tag: "1.4.0"\nsecurityContext:\n  privileged: true\nhostNetwork: true\nresources: {}\n`,
    ],
    ["locales/en.yaml", `errors:\n  privileged: "You do not have permission"\n  kind: "Unknown kind"\n`],
    [
      "k8s/service.yaml",
      `apiVersion: v1\nkind: Service\nmetadata:\n  name: api\nspec:\n  selector:\n    app: api\n  ports:\n    - port: 80\n      targetPort: 8080\n`,
    ],
    [
      "k8s/crd.yaml",
      `apiVersion: acme.io/v1\nkind: Database\nmetadata:\n  name: main\nspec:\n  hostNetwork: true\n  containers:\n    - name: pg\n      image: postgres:16\n`,
    ],
  ];

  for (const [name, content] of corpus) {
    test(`SILENT on ${name}`, async () => {
      assert.deepEqual(await scan(name, content, LIMITS_ON), []);
    });
  }
});
