import { lintSource } from "../src/core/scan.ts";
import { noUnstableOffsetPagination as P } from "../src/diagnostics/bugs/no-unstable-offset-pagination.ts";
import { noUnpinnedDependency as U } from "../src/diagnostics/supplychain/no-unpinned-dependency.ts";
const caps = new Set(["node", "esm", "typescript", "prisma"]);
const np = (s) => lintSource({ filePath: "a.ts", sourceText: s, diagnostics: [P], capabilities: caps }).findings.length;
const nu = (deps) => { let c = 0; U.scan({ filePath: "package.json", normalizedFilePath: "package.json", content: JSON.stringify({ name: "x", dependencies: deps }, null, 2), committed: true, report: () => c++ }); return c; };
let fail = 0;
const w = (l, g, e) => { const ok = g === e; if (!ok) fail++; console.log(`${ok ? "✓" : "✗"} [${g}/${e}] ${l}`); };
w("§141 db.user.findMany skip (TP)", np("db.user.findMany({ skip: 20, take: 10 });"), 1);
w("§141 prisma.user.findMany (TP)", np("prisma.user.findMany({ skip: 20 });"), 1);
w("§141 userRepo.findMany (TP repo)", np("userRepo.findMany({ skip: 20 });"), 1);
w("§141 list.findMany (FP-fixed)", np("list.findMany({ skip: 1 });"), 0);
w("§141 array-literal.findMany (FP-fixed)", np("[1,2,3].findMany({ skip: 1 });"), 0);
w("§141 metrics.aggregate (FP-fixed)", np("metrics.aggregate({ skip: 3 });"), 0);
w("§141 things.groupBy (FP-fixed)", np("things.groupBy({ skip: 2, take: 4 });"), 0);
w("§141 MySQL LIMIT 20,10 (FN-fixed)", np('db.query("SELECT * FROM t LIMIT 20, 10");'), 1);
w("§141 MySQL LIMIT+ORDER (silent)", np('db.query("SELECT * FROM t ORDER BY id LIMIT 20, 10");'), 0);
w("§156 jsr scoped (silent)", nu({ a: "jsr:@foo/bar@^1" }), 0);
w("§156 jsr unscoped ref (FP-fixed)", nu({ a: "jsr:foo/bar#1.0" }), 0);
w("§156 git (TP)", nu({ a: "github:foo/bar" }), 1);
console.log(fail ? `\n${fail} FAILED` : "\nALL PASS");
process.exit(fail ? 1 : 0);
